### ISSUE TITLE
CC2530 support

### ISSUE THREAD

**Issue by Sjord** [wavesoft/CCLib#9]
I have [this CC2530 board](http://www.dx.com/p/cc2530f256rhar-cc2530-zigbee-development-board-w-antenna-green-392654). It seems to work with the CC254X driver. Since the CC2530 and CC2540 share one [user guide](http://www.ti.com/lit/ug/swru191f/swru191f.pdf), it would seem that they are totally compatible. 

I used a [Teensy](https://www.pjrc.com/teensy/) as connector. Since it runs 3.3V, I didn't use any resistors. I short-circuited the pins CC_DD_I and CC_DD_O.

![cc2530](https://cloud.githubusercontent.com/assets/113030/20479297/f9d6560e-afdd-11e6-90f2-cdda61e2bdb4.jpg)

With the CC254X driver, running cc_info.py gives this output:

```
INFO: Found a CC2540/41 chip on /dev/cu.usbmodem2135071

Chip information:
      Chip ID : 0xa524
   Flash size : 256 Kb
    Page size : 2 Kb
    SRAM size : 8 Kb
          USB : No

Device information:
 IEEE Address : 00124b000b0a
           PC : 0000

Debug status:
 [ ] CHIP_ERASE_BUSY
 [ ] PCON_IDLE
 [X] CPU_HALTED
 [ ] PM_ACTIVE
 [ ] HALT_STATUS
 [ ] DEBUG_LOCKED
 [X] OSCILLATOR_STABLE
 [ ] STACK_OVERFLOW

Debug config:
 [ ] SOFT_POWER_MODE
 [ ] TIMERS_OFF
 [X] DMA_PAUSE
 [X] TIMER_SUSPEND
```

I haven't tried running anything else yet. Do you have any suggestions on how to verify this works correctly? If I want CCLib to support the CC2530, should I make a new driver or change the 254X driver? @wavesoft, can I send you this board over the mail so you can test it?

**Comment by wavesoft** [comment]
Hello @Sjord and thanks a lot for sharing your experience! From a quick look, it seems that your arduino can communicate with the debugging interface of the `CC2530`, so first thing is  :heavy_check_mark: 

However to actually perform some flash I/O operations the library will have to invoke CPU instructions, thus making the library chip-dependent. Now, since both chips are sharing the same spec, and since the `CC2540/41` driver already volunteered to handle this chip ID, you might actually be able to write/read from the chip.

Did you by any chance try the `cc_read_flash.py`? If you get some reasonable output (ex. not everything `0xff`) it means that the driver works fine.

Ps. Thanks for the offer to send the board! Since I am in the process of moving and I don't have my lab yet set-up it doesn't make much sense now. I will ping you when I have it ready though ;)

PPs. It might actually make sense to have a newer version of the arduino sketch that supports 3.3v chips. The voltage divider is not really needed nowadays...

**Comment by Sjord** [comment]
I tried `cc_read_flash.py` and it seems to work. It creates [this output file](https://gist.github.com/Sjord/98a68947b65fab98061d29a752b1ff6a).

**Comment by Sjord** [comment]
`cc_write_flash.py` seems to fail:

```
 -> 0x006d : 130 bytes 
    Progress 0%...  
[Flash Error at @0x006d, will retry]

[Flash Error at @0x006e, will retry]

[Flash Error at @0x006f, will retry]
ERROR: Flash verification error on offset 0x0070
```
I will look into this later.

**Comment by wavesoft** [comment]
Hello @Sjord , is the #10 actually closing this issue? Or do you still have issues flashing the chip?

**Comment by Sjord** [comment]
I still have issues flashing this chip, and I think I know why. The flash on the CC2530 (and on the other related hardware) can be written in 4 byte words on 2 KB pages. The [hex file](https://gist.github.com/Sjord/d3ef53b2a5ded6bd2f9598b6412842ff) I use, however, tries to write parts of arbitrary lengths on arbitrary positions. This is not possible in the way CCLib tries to do it currently.

For CCLib to support hex file writing, it first needs to clear any pages that are going to be written and then align each write on a 4 byte word. It currently tries to "overwrite" the flash if you don't use the `--erase` option, which is not possible.

It probably works with a bin file and with the `--erase` option to `cc_write_flash.py`. I will try this out soon. If this works I think this issue can be closed because the CC2530 works just as well as any other chip. However, writing hex files doesn't work properly.

**Comment by wavesoft** [comment]
Ah, I see your problem. And yes, it's true that the current version only writes continuous memory segments.

However, keep in mind that the high-level [`CC254X .writeCODE`](https://github.com/wavesoft/CCLib/blob/master/Python/cclib/chip/cc254x.py#L509) function can already perform a erase+write on arbitrary offsets so it shouldn't be difficult to add non-continuous hex file support to the library. I will create an issue for this and have a look. Thanks for bringing this back to my attention!
